# Generated by Django 4.2.23 on 2025-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
