# Generated by Django 4.2.23 on 2025-06-29 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_studentaccount_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='web.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='web.studentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='web.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='web.studentaccount')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendances', to='web.teacheraccount')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendancerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_processed', False)), fields=('student', 'class_obj'), name='unique_pending_attendance_request'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerequest',
            unique_together={('student', 'class_obj', 'is_processed')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'class_obj', 'date')},
        ),
    ]
