# Generated by Django 4.2.23 on 2025-06-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_attendancerequest_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheraccount',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
